# Fichier de test pour gitleaks - A SUPPRIMER
GITHUB_TOKEN = "ghp_wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY"
AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
